###
GET  http://localhost:9000/roles HTTP/1.1

###
POST http://localhost:9000/roles HTTP/1.1
Content-Type: application/json

{
    "nombreRol"     : "RegistroControl"
}

###
DELETE http://localhost:9000/roles/ HTTP/1.1

### 
PUT http://localhost:9000/roles/3 HTTP/1.1
Content-Type: application/json

{
    "nombreRol"     : "Coordinador"
}